### ISSUE TITLE
Please deploy correct artifact to maven

### ISSUE THREAD

**Issue by Areks** [t9t/jooq-postgresql-json#2] opened 2019-09-12 12:35 UTC
jooq-postgresql-json-parent not deployed to maven, please fix it

**Comment by Globegitter** [comment] 2019-09-23 08:06
@t9t Friendly ping, any chance to get the issue fixed, so we can use this wonderful jooq extension?

**Comment by t9t** [comment] 2019-09-23 08:14
Ah sorry, @Areks and @Globegitter. Somehow I didn't get any notifications or emails about issues on this project. It was your mention that finally triggered an email. I will look into this ASAP!

**Comment by t9t** [comment] 2019-09-23 18:26
I didn't have any experience pushing a multi-module Maven project to OSSRH yet, so I accidentally excluded the parent project (alongside the integration test module, which I saw no point in pushing). I didn't see the issue locally, because it was installed in my local repository.

I was unable to publish the artifact for version 0.3.0 so consider that one nuked. I have pushed 0.3.1 now, which should work fine (I tested it locally after removing the artifacts from my local repository):

```
<dependency>
  <groupId>com.github.t9t.jooq</groupId>
  <artifactId>jooq-postgresql-json</artifactId>
  <version>0.3.1</version>
</dependency>
```

Please let me know if it works!

**Comment by t9t** [comment] 2019-09-24 08:49
Closing as in #1 it was confirmed the dependency works now.

**Closed as completed by t9t** 2019-09-24 08:49 UTC
